# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/harman/_HARMAN Team Project/HarmanSA_June_TeamPJ/hsa_June_app_test1/hsa_June_app_test1.srcs/sources_1/bd/game_cpu/ip/game_cpu_microblaze_0_0/game_cpu_microblaze_0_0.xci
# IP: The module: 'game_cpu_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/harman/_HARMAN Team Project/HarmanSA_June_TeamPJ/hsa_June_app_test1/hsa_June_app_test1.gen/sources_1/bd/game_cpu/ip/game_cpu_microblaze_0_0/game_cpu_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_cpu_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/harman/_HARMAN Team Project/HarmanSA_June_TeamPJ/hsa_June_app_test1/hsa_June_app_test1.gen/sources_1/bd/game_cpu/ip/game_cpu_microblaze_0_0/game_cpu_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_cpu_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/harman/_HARMAN Team Project/HarmanSA_June_TeamPJ/hsa_June_app_test1/hsa_June_app_test1.gen/sources_1/bd/game_cpu/ip/game_cpu_microblaze_0_0/game_cpu_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_cpu_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/harman/_HARMAN Team Project/HarmanSA_June_TeamPJ/hsa_June_app_test1/hsa_June_app_test1.srcs/sources_1/bd/game_cpu/ip/game_cpu_microblaze_0_0/game_cpu_microblaze_0_0.xci
# IP: The module: 'game_cpu_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/harman/_HARMAN Team Project/HarmanSA_June_TeamPJ/hsa_June_app_test1/hsa_June_app_test1.gen/sources_1/bd/game_cpu/ip/game_cpu_microblaze_0_0/game_cpu_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_cpu_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/harman/_HARMAN Team Project/HarmanSA_June_TeamPJ/hsa_June_app_test1/hsa_June_app_test1.gen/sources_1/bd/game_cpu/ip/game_cpu_microblaze_0_0/game_cpu_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_cpu_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/harman/_HARMAN Team Project/HarmanSA_June_TeamPJ/hsa_June_app_test1/hsa_June_app_test1.gen/sources_1/bd/game_cpu/ip/game_cpu_microblaze_0_0/game_cpu_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_cpu_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
