# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/game_cpu/game_cpu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==game_cpu || ORIG_REF_NAME==game_cpu} -quiet] -quiet

# IP: bd/game_cpu/ip/game_cpu_microblaze_0_0/game_cpu_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==game_cpu_microblaze_0_0 || ORIG_REF_NAME==game_cpu_microblaze_0_0} -quiet] -quiet

# IP: bd/game_cpu/ip/game_cpu_dlmb_v10_0/game_cpu_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==game_cpu_dlmb_v10_0 || ORIG_REF_NAME==game_cpu_dlmb_v10_0} -quiet] -quiet

# IP: bd/game_cpu/ip/game_cpu_ilmb_v10_0/game_cpu_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==game_cpu_ilmb_v10_0 || ORIG_REF_NAME==game_cpu_ilmb_v10_0} -quiet] -quiet

# IP: bd/game_cpu/ip/game_cpu_dlmb_bram_if_cntlr_0/game_cpu_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==game_cpu_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==game_cpu_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/game_cpu/ip/game_cpu_ilmb_bram_if_cntlr_0/game_cpu_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==game_cpu_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==game_cpu_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/game_cpu/ip/game_cpu_lmb_bram_0/game_cpu_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==game_cpu_lmb_bram_0 || ORIG_REF_NAME==game_cpu_lmb_bram_0} -quiet] -quiet

# IP: bd/game_cpu/ip/game_cpu_mdm_1_0/game_cpu_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==game_cpu_mdm_1_0 || ORIG_REF_NAME==game_cpu_mdm_1_0} -quiet] -quiet

# IP: bd/game_cpu/ip/game_cpu_clk_wiz_1_0/game_cpu_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==game_cpu_clk_wiz_1_0 || ORIG_REF_NAME==game_cpu_clk_wiz_1_0} -quiet] -quiet

# IP: bd/game_cpu/ip/game_cpu_rst_clk_wiz_1_100M_0/game_cpu_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==game_cpu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==game_cpu_rst_clk_wiz_1_100M_0} -quiet] -quiet

# XDC: c:/harman/_HARMAN Team Project/HarmanSA_June_TeamPJ/hsa_June_app_test1/hsa_June_app_test1.gen/sources_1/bd/game_cpu/game_cpu_ooc.xdc
